/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DataAccesObject.BancoDAO;
import DataAccesObject.DataSource;
import Models.Banco;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author berna
 */
public class JFrameAlterarBanco extends javax.swing.JFrame {

    int cont = 1;

    /**
     * Creates new form JFrameCadastrarBanco
     */
    public JFrameAlterarBanco(Banco b) {

        initComponents();
        //J.getSelectedRow();

        //System.out.println(b.getBairro());
        jTxtCodigo.setText(Integer.toString(b.getCodigo()));
        jTxtBairro.setText(b.getBairro());
        jTxtCidade.setText(b.getCidade());
        jTxtCnpj.setText(b.getCnpj());
        jTxtEstado.setText(b.getEstado());
        jTxtNumero.setText(Integer.toString(b.getNumero()));
        jTxtRazaoSocial.setText(b.getRazaoSocial());
        jTxtTelefone.setText(b.getTelefone());
        jTxtEndereco.setText(b.getEndereco());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAlterarBanco = new javax.swing.JButton();
        labelBairro = new javax.swing.JLabel();
        labelCidade = new javax.swing.JLabel();
        labelRazaoSocial = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelCadastroDeBanco = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelCnpj = new javax.swing.JLabel();
        jTxtRazaoSocial = new javax.swing.JTextField();
        jTxtEstado = new javax.swing.JTextField();
        jTxtNumero = new javax.swing.JTextField();
        jTxtTelefone = new javax.swing.JTextField();
        jTxtCnpj = new javax.swing.JTextField();
        jTxtCodigo = new javax.swing.JTextField();
        jTxtBairro = new javax.swing.JTextField();
        jTxtCidade = new javax.swing.JTextField();
        jTxtEndereco = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        buttonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonAlterarBanco.setText("Alterar");
        buttonAlterarBanco.setToolTipText("");
        buttonAlterarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarBancoActionPerformed(evt);
            }
        });

        labelBairro.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelBairro.setText("Bairro");

        labelCidade.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelCidade.setText("Cidade");

        labelRazaoSocial.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelRazaoSocial.setText("Razao Social");

        labelEstado.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelEstado.setText("Estado");

        labelCadastroDeBanco.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelCadastroDeBanco.setText("Cadastro de Banco");

        labelCodigo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelCodigo.setText("Codigo");

        labelNumero.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelNumero.setText("Número");

        labelTelefone.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelTelefone.setText("Telefone");

        labelCnpj.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelCnpj.setText("Cnpj");

        jTxtRazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRazaoSocialActionPerformed(evt);
            }
        });

        jTxtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEstadoActionPerformed(evt);
            }
        });

        jTxtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTelefoneActionPerformed(evt);
            }
        });

        jTxtCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCnpjActionPerformed(evt);
            }
        });

        jTxtCodigo.setEditable(false);

        jTxtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEnderecoActionPerformed(evt);
            }
        });

        labelEndereco.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelEndereco.setText("Endereço");

        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(labelCadastroDeBanco)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCodigo)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBairro)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(324, 324, 324)
                            .addComponent(labelNumero))
                        .addComponent(labelRazaoSocial, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jTxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(labelCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(189, 189, 189)
                            .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTxtRazaoSocial, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTxtNumero))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelCidade)
                                        .addGap(216, 216, 216))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelEstado)
                                .addComponent(jTxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonAlterarBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastroDeBanco)
                .addGap(18, 18, 18)
                .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAlterarBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private boolean validaAlterar() {
        if (jTxtRazaoSocial.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "razão social invalido");
            return false;
        }
        if (jTxtCnpj.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " cnpj invalido");
            return false;
        }
        if (jTxtTelefone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Telefoneinvalido");
            return false;
        }
        if (jTxtNumero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Numero invalido");
            return false;
        }
        if (jTxtBairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bairro invalido");
            return false;
        }
        if (jTxtCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Cidade invalido");
            return false;
        }
        if (jTxtEstado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Estado invalido");
            return false;
        }
        
        return true;

    }
    private void buttonAlterarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarBancoActionPerformed
        // TODO add your handling code here:
        if (validaAlterar() == false) {
            return;
        }
        Banco b = new Banco();
        //b.setCodigo(Integer.toString(cod));
        b.setBairro(jTxtBairro.getText());
        b.setCidade(jTxtCidade.getText());
        b.setCnpj(jTxtCnpj.getText());
        b.setEstado(jTxtEstado.getText());
        b.setNumero(Integer.parseInt(jTxtNumero.getText()));
        b.setRazaoSocial(jTxtRazaoSocial.getText());
        b.setTelefone(jTxtTelefone.getText());
        b.setEndereco(jTxtEndereco.getText());

        try {
            BancoDAO banco = new BancoDAO();
            banco.alterarBanco(b, b.getCodigo());
            
            JOptionPane.showMessageDialog(null, "Banco alterado com sucesso");
            jTxtBairro.setText("");
            jTxtCidade.setText("");
            jTxtCnpj.setText("");
            jTxtCodigo.setText("");
            jTxtEstado.setText("");
            jTxtNumero.setText("");
            jTxtRazaoSocial.setText("");
            jTxtTelefone.setText("");
            jTxtEndereco.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha!" + e.getMessage());
        }
    }//GEN-LAST:event_buttonAlterarBancoActionPerformed

    private void jTxtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEstadoActionPerformed

    private void jTxtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEnderecoActionPerformed

    private void jTxtRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRazaoSocialActionPerformed

    private void jTxtCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCnpjActionPerformed

    private void jTxtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTelefoneActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        dispose();
    }//GEN-LAST:event_buttonSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterarBanco;
    private javax.swing.JButton buttonSair;
    private javax.swing.JTextField jTxtBairro;
    private javax.swing.JTextField jTxtCidade;
    private javax.swing.JTextField jTxtCnpj;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtEndereco;
    private javax.swing.JTextField jTxtEstado;
    private javax.swing.JTextField jTxtNumero;
    private javax.swing.JTextField jTxtRazaoSocial;
    private javax.swing.JTextField jTxtTelefone;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCadastroDeBanco;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCnpj;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelRazaoSocial;
    private javax.swing.JLabel labelTelefone;
    // End of variables declaration//GEN-END:variables
}
