/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DataAccesObject.BancoDAO;
import DataAccesObject.FiadorDAO;
import DataAccesObject.ImovelDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Joana
 */
public class JFrameRelatorios extends javax.swing.JFrame {

    /**
     * Creates new form JFrameBuscarFiador
     */
    public JFrameRelatorios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFiador = new javax.swing.JLabel();
        jButtonSair1 = new javax.swing.JButton();
        jButtonBuscarimovel = new javax.swing.JButton();
        jButtonBuscarimovel1 = new javax.swing.JButton();
        jButtonBuscarimovel2 = new javax.swing.JButton();
        jButtonBuscarimovel3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFiador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelFiador.setText("Relatórios");

        jButtonSair1.setText("Sair");
        jButtonSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSair1ActionPerformed(evt);
            }
        });

        jButtonBuscarimovel.setText("Relatório de todos os Imóveis");
        jButtonBuscarimovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarimovelActionPerformed(evt);
            }
        });

        jButtonBuscarimovel1.setText("Relatório de Imóveis Disponíveis");
        jButtonBuscarimovel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarimovel1ActionPerformed(evt);
            }
        });

        jButtonBuscarimovel2.setText("Relatório de Imóveis Reservados");
        jButtonBuscarimovel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarimovel2ActionPerformed(evt);
            }
        });

        jButtonBuscarimovel3.setText("Relatório de Imóveis Vendidos");
        jButtonBuscarimovel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarimovel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBuscarimovel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarimovel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarimovel2)
                            .addComponent(jButtonBuscarimovel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFiador, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelFiador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButtonBuscarimovel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarimovel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jButtonBuscarimovel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButtonBuscarimovel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jButtonSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSair1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSair1ActionPerformed

    private void jButtonBuscarimovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarimovelActionPerformed
        // TODO add your handling code here:
         try {
            ImovelDAO i = new ImovelDAO();
            i.RelatorioImoveis();
            JOptionPane.showMessageDialog(null, "Exibindo Relatorio...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "olla!" + e.getMessage());
        }    
    }//GEN-LAST:event_jButtonBuscarimovelActionPerformed

    private void jButtonBuscarimovel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarimovel1ActionPerformed
        // TODO add your handling code here:
        try {
            ImovelDAO i = new ImovelDAO();
            i.RelatorioDisponivel();
            JOptionPane.showMessageDialog(null, "Exibindo Relatorio...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "olla!" + e.getMessage());
        }            
    }//GEN-LAST:event_jButtonBuscarimovel1ActionPerformed

    private void jButtonBuscarimovel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarimovel2ActionPerformed
        // TODO add your handling code here:
         try {
            ImovelDAO i = new ImovelDAO();
            i.RelatorioReserva();
            JOptionPane.showMessageDialog(null, "Exibindo Relatorio...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "olla!" + e.getMessage());
        }     
    }//GEN-LAST:event_jButtonBuscarimovel2ActionPerformed

    private void jButtonBuscarimovel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarimovel3ActionPerformed
        // TODO add your handling code here:
        try {
            ImovelDAO i = new ImovelDAO();
            i.RelatorioVenda();
            JOptionPane.showMessageDialog(null, "Exibindo Relatorio...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "olla!" + e.getMessage());
        }   
    }//GEN-LAST:event_jButtonBuscarimovel3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarimovel;
    private javax.swing.JButton jButtonBuscarimovel1;
    private javax.swing.JButton jButtonBuscarimovel2;
    private javax.swing.JButton jButtonBuscarimovel3;
    private javax.swing.JButton jButtonSair1;
    private javax.swing.JLabel jLabelFiador;
    // End of variables declaration//GEN-END:variables
}
