/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Sessao;

/**
 *
 * @author aluno
 */
public class JFrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenulPrincipal
     * @param cpf
     * @param tipoUsuario
     */
   public JFrameMenu(String cpf, String tipoUsuario) 
    {        
        Sessao sessao = new Sessao();
        sessao.iniciaSessao(cpf, tipoUsuario);
        
        initComponents();    
        
        if(sessao.getSessao().equals("corretor"))
        {
            jMenuCorretor.setVisible(false);
            subMenuAlteraImoveis.setVisible(false);
            subMenuCadImoveis.setVisible(false);
            MenuFiador.setVisible(false);
            menuBanco.setVisible(false);
            jMenuVendas.setVisible(false);
            jMenuDeslogarA.setVisible(false);
            subMenuReservaImoveis.setVisible(false);
        }else if(sessao.getSessao().equals("administrador"))
            {
              jMenuDeslogarC.setVisible(false); 
              jMenuBuscarImovel.setVisible(false);
              jMenuReserva.setVisible(false);
            }
        
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarPrincipal = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        jMenuComprador = new javax.swing.JMenu();
        jMenuBuscarComprador = new javax.swing.JMenuItem();
        jMenuCadastrarComprador = new javax.swing.JMenuItem();
        jMenuCorretor = new javax.swing.JMenu();
        jMenuBuscarCorretor = new javax.swing.JMenuItem();
        jMenuCadastrarCorretor = new javax.swing.JMenuItem();
        menuImovel = new javax.swing.JMenu();
        subMenuCadImoveis = new javax.swing.JMenuItem();
        subMenuAlteraImoveis = new javax.swing.JMenuItem();
        jMenuBuscarImovel = new javax.swing.JMenuItem();
        MenuFiador = new javax.swing.JMenu();
        subMenuCadFiador = new javax.swing.JMenuItem();
        subMenuBuscFiador = new javax.swing.JMenuItem();
        menuBanco = new javax.swing.JMenu();
        subMenuCadBanco = new javax.swing.JMenuItem();
        subMenuBuscBanco = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        subMenuVendaImoveis = new javax.swing.JMenuItem();
        jMenuReservas = new javax.swing.JMenu();
        subMenuReservaImoveis = new javax.swing.JMenuItem();
        jMenuReserva = new javax.swing.JMenuItem();
        jMenuRelatórios = new javax.swing.JMenu();
        jMenuRelatorios = new javax.swing.JMenuItem();
        jMenuDeslogarA = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenuItem();
        jMenuDeslogarC = new javax.swing.JMenu();
        jMenuSair1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuUsuarios.setText("Cadastro de Pessoas");

        jMenuComprador.setText("Comprador");

        jMenuBuscarComprador.setText("Buscar - Alterar/Excluir");
        jMenuBuscarComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarCompradorActionPerformed(evt);
            }
        });
        jMenuComprador.add(jMenuBuscarComprador);

        jMenuCadastrarComprador.setText("Cadastrar");
        jMenuCadastrarComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarCompradorActionPerformed(evt);
            }
        });
        jMenuComprador.add(jMenuCadastrarComprador);

        menuUsuarios.add(jMenuComprador);

        jMenuCorretor.setText("Corretor");

        jMenuBuscarCorretor.setText("Buscar - Alterar/Excluir");
        jMenuBuscarCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarCorretorActionPerformed(evt);
            }
        });
        jMenuCorretor.add(jMenuBuscarCorretor);

        jMenuCadastrarCorretor.setText("Cadastrar");
        jMenuCadastrarCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarCorretorActionPerformed(evt);
            }
        });
        jMenuCorretor.add(jMenuCadastrarCorretor);

        menuUsuarios.add(jMenuCorretor);

        menuBarPrincipal.add(menuUsuarios);

        menuImovel.setText("Gerenciar Imóveis");

        subMenuCadImoveis.setText("Cadastrar");
        subMenuCadImoveis.setActionCommand("Cadastrar/Excluir");
        subMenuCadImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadImoveisActionPerformed(evt);
            }
        });
        menuImovel.add(subMenuCadImoveis);

        subMenuAlteraImoveis.setText("Buscar-Alterar/Excluir");
        subMenuAlteraImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuAlteraImoveisActionPerformed(evt);
            }
        });
        menuImovel.add(subMenuAlteraImoveis);

        jMenuBuscarImovel.setText("Buscar");
        jMenuBuscarImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarImovelActionPerformed(evt);
            }
        });
        menuImovel.add(jMenuBuscarImovel);

        menuBarPrincipal.add(menuImovel);

        MenuFiador.setText("Gerenciar  Fiador");

        subMenuCadFiador.setText("Cadastrar");
        subMenuCadFiador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadFiadorActionPerformed(evt);
            }
        });
        MenuFiador.add(subMenuCadFiador);

        subMenuBuscFiador.setText("Buscar - Alterar/Excluir");
        subMenuBuscFiador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuBuscFiadorActionPerformed(evt);
            }
        });
        MenuFiador.add(subMenuBuscFiador);

        menuBarPrincipal.add(MenuFiador);

        menuBanco.setText("Gerenciar Bancos");

        subMenuCadBanco.setText("Cadastrar");
        subMenuCadBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadBancoActionPerformed(evt);
            }
        });
        menuBanco.add(subMenuCadBanco);

        subMenuBuscBanco.setText("Buscar - Alterar/Excluir");
        subMenuBuscBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuBuscBancoActionPerformed(evt);
            }
        });
        menuBanco.add(subMenuBuscBanco);

        menuBarPrincipal.add(menuBanco);

        jMenuVendas.setText("Vendas");

        subMenuVendaImoveis.setText("Vender/Cancelar Venda");
        subMenuVendaImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuVendaImoveisActionPerformed(evt);
            }
        });
        jMenuVendas.add(subMenuVendaImoveis);

        menuBarPrincipal.add(jMenuVendas);

        jMenuReservas.setText("Reservas");

        subMenuReservaImoveis.setText("Reservar/Cancelar Reserva");
        subMenuReservaImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuReservaImoveisActionPerformed(evt);
            }
        });
        jMenuReservas.add(subMenuReservaImoveis);

        jMenuReserva.setText("Reservar/Cancelar Reserva");
        jMenuReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReservaActionPerformed(evt);
            }
        });
        jMenuReservas.add(jMenuReserva);

        menuBarPrincipal.add(jMenuReservas);

        jMenuRelatórios.setText("Relatórios");

        jMenuRelatorios.setText("Exibir Relatórios");
        jMenuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatoriosActionPerformed(evt);
            }
        });
        jMenuRelatórios.add(jMenuRelatorios);

        menuBarPrincipal.add(jMenuRelatórios);

        jMenuDeslogarA.setBackground(new java.awt.Color(0, 255, 51));
        jMenuDeslogarA.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jMenuDeslogarA.setForeground(new java.awt.Color(0, 255, 51));
        jMenuDeslogarA.setText("Administrador:::Logado");

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuDeslogarA.add(jMenuSair);

        menuBarPrincipal.add(jMenuDeslogarA);

        jMenuDeslogarC.setBackground(new java.awt.Color(0, 255, 102));
        jMenuDeslogarC.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jMenuDeslogarC.setForeground(new java.awt.Color(0, 255, 51));
        jMenuDeslogarC.setText("Corretor:::Logado");

        jMenuSair1.setText("Sair");
        jMenuSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSair1ActionPerformed(evt);
            }
        });
        jMenuDeslogarC.add(jMenuSair1);

        menuBarPrincipal.add(jMenuDeslogarC);

        setJMenuBar(menuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 989, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuCadImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadImoveisActionPerformed
        JFrameCadastrarImovel cadImovel = new JFrameCadastrarImovel();
        cadImovel.show();
    }//GEN-LAST:event_subMenuCadImoveisActionPerformed

    private void jMenuCadastrarCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarCorretorActionPerformed
        // TODO add your handling code here:
        JFrameCadastroCorretor cadCorretor = new JFrameCadastroCorretor();
        cadCorretor.show();
    }//GEN-LAST:event_jMenuCadastrarCorretorActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void subMenuVendaImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuVendaImoveisActionPerformed
        JFrameBuscarImovel buscImovel = new JFrameBuscarImovel();
        buscImovel.show();
    }//GEN-LAST:event_subMenuVendaImoveisActionPerformed

    private void jMenuBuscarCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarCorretorActionPerformed
        JFrameBuscarCorretor buscCorretor = new JFrameBuscarCorretor();
        buscCorretor.show();

    }//GEN-LAST:event_jMenuBuscarCorretorActionPerformed

    private void jMenuBuscarCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarCompradorActionPerformed
        JFrameBuscarComprador buscComprador = new JFrameBuscarComprador();
        buscComprador.show();


    }//GEN-LAST:event_jMenuBuscarCompradorActionPerformed

    private void jMenuCadastrarCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarCompradorActionPerformed
        JFrameCadastrarComprador cadComprador = new JFrameCadastrarComprador();
        cadComprador.show();

    }//GEN-LAST:event_jMenuCadastrarCompradorActionPerformed

    private void subMenuCadFiadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadFiadorActionPerformed
        JFrameCadastrarFiador cadFiador = new JFrameCadastrarFiador();
        cadFiador.show();
    }//GEN-LAST:event_subMenuCadFiadorActionPerformed

    private void subMenuReservaImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuReservaImoveisActionPerformed
        JFrameBuscarImovel buscImovel = new JFrameBuscarImovel();
        buscImovel.show();
    }//GEN-LAST:event_subMenuReservaImoveisActionPerformed

    private void subMenuCadBancoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_subMenuCadBancoActionPerformed
    {//GEN-HEADEREND:event_subMenuCadBancoActionPerformed
        JFrameCadastrarBanco cadBanco = new JFrameCadastrarBanco();
        cadBanco.show();
    }//GEN-LAST:event_subMenuCadBancoActionPerformed

    private void subMenuBuscBancoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_subMenuBuscBancoActionPerformed
    {//GEN-HEADEREND:event_subMenuBuscBancoActionPerformed
        JFrameBuscarBanco buscBanco = new JFrameBuscarBanco();
        buscBanco.show();
    }//GEN-LAST:event_subMenuBuscBancoActionPerformed

    private void subMenuAlteraImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuAlteraImoveisActionPerformed
        JFrameBuscarImovel buscImovel = new JFrameBuscarImovel();
        buscImovel.show();
    }//GEN-LAST:event_subMenuAlteraImoveisActionPerformed

    private void subMenuBuscFiadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuBuscFiadorActionPerformed
        JFrameBuscarFiador buscFiador = new JFrameBuscarFiador();
        buscFiador.show();
    }//GEN-LAST:event_subMenuBuscFiadorActionPerformed

    private void jMenuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatoriosActionPerformed
        // TODO add your handling code here:
        JFrameRelatorios todos = new JFrameRelatorios();
        todos.show();
    }//GEN-LAST:event_jMenuRelatoriosActionPerformed

    private void jMenuSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSair1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuSair1ActionPerformed

    private void jMenuBuscarImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarImovelActionPerformed
        // TODO add your handling code here:
        JFrameBuscarImovelCorretor buscImovel = new JFrameBuscarImovelCorretor();
        buscImovel.show();
    }//GEN-LAST:event_jMenuBuscarImovelActionPerformed

    private void jMenuReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReservaActionPerformed
        // TODO add your handling code here:
        JFrameBuscarImovelCorretor buscImovel = new JFrameBuscarImovelCorretor();
        buscImovel.show();
    }//GEN-LAST:event_jMenuReservaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuFiador;
    private javax.swing.JMenuItem jMenuBuscarComprador;
    private javax.swing.JMenuItem jMenuBuscarCorretor;
    private javax.swing.JMenuItem jMenuBuscarImovel;
    private javax.swing.JMenuItem jMenuCadastrarComprador;
    private javax.swing.JMenuItem jMenuCadastrarCorretor;
    private javax.swing.JMenu jMenuComprador;
    private javax.swing.JMenu jMenuCorretor;
    private javax.swing.JMenu jMenuDeslogarA;
    private javax.swing.JMenu jMenuDeslogarC;
    private javax.swing.JMenuItem jMenuRelatorios;
    private javax.swing.JMenu jMenuRelatórios;
    private javax.swing.JMenuItem jMenuReserva;
    private javax.swing.JMenu jMenuReservas;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenuItem jMenuSair1;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JMenu menuBanco;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenu menuImovel;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenuItem subMenuAlteraImoveis;
    private javax.swing.JMenuItem subMenuBuscBanco;
    private javax.swing.JMenuItem subMenuBuscFiador;
    private javax.swing.JMenuItem subMenuCadBanco;
    private javax.swing.JMenuItem subMenuCadFiador;
    private javax.swing.JMenuItem subMenuCadImoveis;
    private javax.swing.JMenuItem subMenuReservaImoveis;
    private javax.swing.JMenuItem subMenuVendaImoveis;
    // End of variables declaration//GEN-END:variables
}
