/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DataAccesObject.BancoDAO;
import DataAccesObject.CompradorDAO;
import DataAccesObject.FiadorDAO;
import DataAccesObject.ImovelDAO;
import DataAccesObject.VendaEReservaDAO;
import Models.Banco;
import Models.Comprador;
import Models.Fiador;
import Models.Imovel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joana
 */
public class JFrameFinanciarImovel extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCadastroImovel
     */
    public JFrameFinanciarImovel(int codImovel, int codComprador) {
        initComponents();
        listarFiadorTodos();
        listarBancosTodos();
        jTxtCodComprador.setText(Integer.toString(codComprador));
        jTxtCodImovel.setText(Integer.toString(codImovel));
        /*
        jTxtCodigo.setText(Integer.toString(i.getCodigo()));
        jComboBoxTipo.setSelectedIndex(Integer.parseInt(i.getTipo()));
        jTxtDescricao.setText(i.getDescricao());
        jTxtEndereco.setText(i.getEndereco());
        jTxtNumero.setText(Integer.toString(i.getNumero()));
        jTxtBairro.setText(i.getBairro());
        jTxtCidade.setText(i.getCidade());
        jComboBoxEstado.setSelectedIndex(Integer.parseInt(i.getEstado()));
        jTxtComplemento.setText(i.getComplemento());
        jTxtValor.setText(Float.toString(i.getValor()));
        */

    }
    
    
    
    private void listarFiadorTodos() {
        try {
            FiadorDAO fiador = new FiadorDAO();
            ArrayList<Fiador> fiadores = fiador.listarFiadorTodos();
            DefaultTableModel limpar = (DefaultTableModel) jTableFiador.getModel();
            limpar.setNumRows(0);
            for (Fiador f : fiadores) {
                DefaultTableModel model = (DefaultTableModel) jTableFiador.getModel();
                Object linha[] = new Object[]{f.getCodigo(), f.getNome(), f.getEndereco(), f.getNumero(), f.getBairro(), f.getCidade(), f.getEstado(), f.getCpf(), f.getTelefone()};
                model.addRow(linha);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao exibir bancos.");
        }
    }
    private void listarBancosTodos() {
        try {
            BancoDAO banco = new BancoDAO();
            ArrayList<Banco> bancos = banco.listarBancoTodos();
            DefaultTableModel limpar = (DefaultTableModel) jTableBanco.getModel();
            limpar.setNumRows(0);
            for (Banco b : bancos) {
                DefaultTableModel model = (DefaultTableModel) jTableBanco.getModel();
                Object linha[] = new Object[]{b.getCodigo(), b.getRazaoSocial(), b.getCnpj(), b.getEndereco(), b.getNumero(), b.getBairro(), b.getCidade(), b.getEstado(), b.getTelefone()};
                model.addRow(linha);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao exibir bancos.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        labelCadastroDeImovel = new javax.swing.JLabel();
        buttonVender = new javax.swing.JButton();
        jLabelImovel = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jLabelComprador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBanco = new javax.swing.JTable();
        jButtonBuscar1 = new javax.swing.JButton();
        jTxtBanco = new javax.swing.JTextField();
        jTxtFiador = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFiador = new javax.swing.JTable();
        jButtonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtCodImovel = new javax.swing.JTextField();
        jTxtCodComprador = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCadastroDeImovel.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelCadastroDeImovel.setText("Vender Imóvel");

        buttonVender.setText("Vender");
        buttonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVenderActionPerformed(evt);
            }
        });

        jLabelImovel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelImovel.setText("Banco:");

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabelComprador.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelComprador.setText("Fiador");

        jTableBanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Razão Social", "Cnpj", "Telefone "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableBanco);

        jButtonBuscar1.setText("Buscar");
        jButtonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscar1ActionPerformed(evt);
            }
        });

        jTxtBanco.setText("pesquisar pela razao social");
        jTxtBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBancoActionPerformed(evt);
            }
        });
        jTxtBanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtBancoKeyPressed(evt);
            }
        });

        jTxtFiador.setText("pesquisar pelo nome");
        jTxtFiador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFiadorActionPerformed(evt);
            }
        });
        jTxtFiador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtFiadorKeyPressed(evt);
            }
        });

        jTableFiador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableFiador);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Código Imovel:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Código Comprador:");

        jTxtCodImovel.setEditable(false);
        jTxtCodImovel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jTxtCodComprador.setEditable(false);
        jTxtCodComprador.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(labelCadastroDeImovel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtCodImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCodComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTxtFiador, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar))
                    .addComponent(jLabelImovel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelComprador, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTxtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(buttonVender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(labelCadastroDeImovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCodImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtCodComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabelComprador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFiador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVenderActionPerformed
        Banco b = new Banco();
        Fiador f = new Fiador();
        int imovel = Integer.parseInt(jTxtCodImovel.getText());
        int comprador = Integer.parseInt(jTxtCodComprador.getText());
        b.setCodigo((int) jTableBanco.getValueAt(jTableBanco.getSelectedRow(), 0));
        f.setCodigo((int) jTableFiador.getValueAt(jTableFiador.getSelectedRow(), 0));
        try {
                VendaEReservaDAO venda = new VendaEReservaDAO();
                venda.vendaComBanco(imovel, comprador, b.getCodigo(), f.getCodigo());

                JOptionPane.showMessageDialog(null, "Imóvel vendido com sucesso");
                dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha!" + e.getMessage());
            }
    }//GEN-LAST:event_buttonVenderActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscar1ActionPerformed
        //table = (JTable)JTable.getModel();
        //table.setNumRows(0);
        try {
            BancoDAO banco = new BancoDAO();
            ArrayList<Banco> bancos = banco.listarBanco(jTxtBanco.getText());
            DefaultTableModel limpar = (DefaultTableModel) jTableBanco.getModel();
            limpar.setNumRows(0);
            for (Banco b : bancos) {
                DefaultTableModel model = (DefaultTableModel) jTableBanco.getModel();
                Object linha[] = new Object[]{b.getCodigo(), b.getRazaoSocial(), b.getCnpj(), b.getEndereco(), b.getNumero(), b.getBairro(), b.getCidade(), b.getEstado(), b.getTelefone()};
                model.addRow(linha);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao exibir bancos.");
        }
    }//GEN-LAST:event_jButtonBuscar1ActionPerformed

    private void jTxtBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBancoActionPerformed

    private void jTxtBancoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtBancoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBancoKeyPressed

    private void jTxtFiadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFiadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFiadorActionPerformed

    private void jTxtFiadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFiadorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFiadorKeyPressed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        //table = (JTable)JTable.getModel();
        //table.setNumRows(0);
        try {
            FiadorDAO fiador = new FiadorDAO();
            ArrayList<Fiador> fiadores = fiador.listarFiador(jTxtFiador.getText());
            DefaultTableModel limpar = (DefaultTableModel) jTableFiador.getModel();
            limpar.setNumRows(0);
            for (Fiador f : fiadores) {
                DefaultTableModel model = (DefaultTableModel) jTableFiador.getModel();
                Object linha[] = new Object[]{f.getCodigo(), f.getNome(), f.getEndereco(), f.getNumero(), f.getBairro(), f.getCidade(), f.getEstado(), f.getCpf(), f.getTelefone()};
                model.addRow(linha);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao exibir bancos.");
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonVender;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscar1;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelComprador;
    private javax.swing.JLabel jLabelImovel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableBanco;
    private javax.swing.JTable jTableFiador;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtBanco;
    private javax.swing.JTextField jTxtCodComprador;
    private javax.swing.JTextField jTxtCodImovel;
    private javax.swing.JTextField jTxtFiador;
    private javax.swing.JLabel labelCadastroDeImovel;
    // End of variables declaration//GEN-END:variables
}
